version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  www:
    image: koromerzhin/php:8.4.13-apache
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
      - ${PWD}/conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ${PWD}/conf/apache2/apache2.conf:/etc/apache2/apache2.conf:ro
    networks:
      - net
      - proxylampy
      - serverlampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.joomla.rule=Host(`joomla.traefik.me`)"
        - "traefik.http.routers.joomla-tls.tls.domains[0].main=joomla.traefik.me"
        - "traefik.http.routers.joomla.tls=true"
        - "traefik.http.services.joomla.loadbalancer.server.port=80"