version: "3.4"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true

volumes:
  mariadb_data:

services:
  apache:
    image: httpd:2.4.48
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.joomla.rule=HostRegexp(`joomla.traefik.me`, `joomla.{ip:.*}.traefik.me`)"
        - "traefik.http.services.joomla.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:7.4.12
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - serverlampy
    deploy:
      labels:
        - "traefik.enable=false"
